#!/usr/bin/env python

'''
given cluster_info.json generated by 
~/proj/imaging/electron/frequent_structure/classification-cpp/tomominer/tomominer/simulation/individual/subtomogram_generation.py

we export ground truth subtomograms into certain place, also add PDB id into file name, for easy manual inspection

'''

import os, json, shutil

if __name__ == '__main__':
    with open('export_ground_truth__op.json') as f:     op = json.load(f)

    with open(op['cluster_info_file']) as f:        ci = json.load(f)


    for c in ci:
        fn = c['ground_truth']
        fn_dir = os.path.dirname(fn)
        fn_root, fn_ext = os.path.splitext(     os.path.basename(fn)        )

        fn_out = os.path.join(op['out_dir'], fn_root + '-' + c['pdb_id'] + fn_ext)
        assert not os.path.isfile(fn_out)

        print fn_out
        shutil.copyfile(fn, fn_out)
        

