#!/usr/bin/env python



'''
given the membrane segments generated by such programs as 
~/ln/tomominer/tomominer/image/feature/surface_feature__segment.py

we eliminate those peaks that are located on the membrane segments

'''


if __name__ == '__main__':

    print 'warning, this procedure may reduce the chance to detect membrane bound macromolecular complexes!!'

    import json
    with open('peak_membrane_elimination__op.json') as f:   op = json.load(f)

    with open(op['peak_file']) as f:        pp = json.load(f)

    import tomominer.io.file as IF
    s = IF.read_mrc(op['segment_file'])['value']        # membrane segment

    import numpy as N
    siz_seg = N.array(s.shape)

    mrc_full = IF.read_mrc(op['full_tomogram_file'], read_data=False)['header']['MRC']
    siz_full = N.array(     [mrc_full['nx'], mrc_full['ny'], mrc_full['nz']]     )


    pp_f = []
    for p in pp:
        x = p['x']

        # rescale the point coordinate from the full map to the segment map
        xs = [N.round(siz_seg[_]*(float(x[_])/siz_full[_])) for _ in range(len(x))]

        if (xs[0]>=siz_seg[0]) or (xs[1]>=siz_seg[1]) or (xs[2]>=siz_seg[2]):   continue

        if s[xs[0], xs[1], xs[2]] >= 0.5:   continue        # ignore when the peak is on the membrane region

        pp_f.append(p)

    print 'peak number reduced from', len(pp), 'to', len(pp_f)
    with open('peak_membrane_elimination__out.json', 'w') as f:     json.dump(pp_f, f, indent=2)

